tinyMCE.addI18n('en.advanced',{
style_select:"Стили",
font_size:"Размер шрифта",
fontdefault:"Название шрифта",
block:"Форматированный текст",
paragraph:"Обзацами",
div:"DIV",
address:"Адрес",
pre:"Заренее отформатированный текст",
h1:"Заголовок 1",
h2:"Заголовок 2",
h3:"Заголовок 3",
h4:"Заголовок 4",
h5:"Заголовок 5",
h6:"Заголовок 6",
blockquote:"Кавычки",
code:"Код",
samp:"Пример кода",
dt:"Определение значения",
dd:"Описание значения",
bold_desc:"Жирный (Ctrl+B)",
italic_desc:"Наклонный (Ctrl+I)",
underline_desc:"Подчеркнутый (Ctrl+U)",
striketrough_desc:"Strikethrough",
justifyleft_desc:"По левому краю",
justifycenter_desc:"По центру",
justifyright_desc:"По правому краю",
justifyfull_desc:"По ширине страницы",
bullist_desc:"Простой список",
numlist_desc:"Нумерованный список",
outdent_desc:"Выступ строки",
indent_desc:"Отступ строки",
undo_desc:"Отменить изменение (Ctrl+Z)",
redo_desc:"Вернуть измениение (Ctrl+Y)",
link_desc:"Добавить/изменить ссылку",
unlink_desc:"Убрать ссылку",
image_desc:"Добавить/изменить изображение",
cleanup_desc:"Выполнить чистку кода",
code_desc:"Редактор HTML",
sub_desc:"Нижний индекс",
sup_desc:"Верхний индекс",
hr_desc:"Вставить горизонтальную линейку",
removeformat_desc:"Убрать форматирование",
custom1_desc:"Описание",
forecolor_desc:"Выбрать цвет текста",
backcolor_desc:"Выбрать цвет фона",
charmap_desc:"Вставить символ",
visualaid_desc:"Включить/отключить guidelines/invisible elements",
anchor_desc:"Добавить/изменить ссылку",
cut_desc:"Вырезать",
copy_desc:"Копировать",
paste_desc:"Вставить",
image_props_desc:"Свойства изображения",
newdocument_desc:"Новый документ",
help_desc:"Помощь",
blockquote_desc:"Кавычки",
clipboard_msg:"Копировать/Вырезать/Вставить не доступно в Mozilla and Firefox.\n Дополнительная информация по данному вопросу?",
path:"Путь",
newdocument:"Вы уверены, что хотите удалить все содержимое?",
toolbar_focus:"Перейти на кнопки инструментов - Alt+Q, Вернуться в редактор - Alt-Z, Перейти к пути к элементу - Alt-X",
more_colors:"Больше цветов"
});