tinyMCE.addI18n('en.advanced_dlg',{
about_title:"О TinyMCE",
about_general:"О программе",
about_help:"Помощь",
about_license:"Лицензия",
about_plugins:"Дополнения",
about_plugin:"Дополнение",
about_author:"Автор",
about_version:"Версия",
about_loaded:"Подключенные дополнения",
anchor_title:"Добавить/изменить ссылку",
anchor_name:"Текст ссылки",
code_title:"Редактор HTML",
code_wordwrap:"Обтекание теккстом",
colorpicker_title:"Выбрать цвет",
colorpicker_picker_tab:"Выбор цвета",
colorpicker_picker_title:"Выбор цвета",
colorpicker_palette_tab:"Палитра",
colorpicker_palette_title:"Цвет палитры",
colorpicker_named_tab:"Выбранные",
colorpicker_named_title:"Выбранные цвета",
colorpicker_color:"Цвет:",
colorpicker_name:"Название:",
charmap_title:"Выбрать спец символ",
image_title:"Добавить/изменить изображение",
image_src:"Адрес изображения",
image_alt:"Описание изображения",
image_list:"Список изображений",
image_border:"Граница",
image_dimensions:"Размеры",
image_vspace:"По вертикали",
image_hspace:"По гоирзонтали",
image_align:"Выравнивание",
image_align_baseline:"Без выравнивания",
image_align_top:"По верхнему краю",
image_align_middle:"По центру",
image_align_bottom:"По нижнему краю",
image_align_texttop:"Текст по верхнему краю",
image_align_textbottom:"Текст по инжнему краю",
image_align_left:"По левому краю",
image_align_right:"По правому краю",
link_title:"Добавить/изменить ссылку",
link_url:"Адрес ссылки",
link_target:"Окно для ссылки",
link_target_same:"Открыть ссылку в том же самом окне",
link_target_blank:"Открыть ссылку в новом окне",
link_titlefield:"Описание",
link_is_email:"Адресс введенный вами является адресом электронной почты, желаете добавить префикс mailto:?",
link_is_external:"Адрес введенный вами является внешним адресом, желаете добавить необходимый префикс http:// ?",
link_list:"Список ссылок"
});